### ISSUE TITLE
result data seems to desync on some search-terms

### ISSUE THREAD

**Issue by stefan-karger** [create-signal/cmdk-solid#1]
This is based on this issue:
https://github.com/sek-consulting/solid-ui/issues/120

I built a repro:
https://github.com/sek-consulting/cmdk-desync
https://cmdk-desync.vercel.app/

I really hope that using solid-ui isn't causing this but this was a lot quicker then manually building the ui again. Especially since it's only an ui wrapper around the component.

The issue:
You can search anything like `about`, `install`, `button`, `command`, delete it and search something different.
The results will always represent the current input.
But once you input `bar` and delete the `r` is when the result seems to freeze or desync. If you delete the rest and try to search for something new, the result won't change.

If you need some more info or help, just let me know.

**Comment by create-signal** [comment]
Thanks for this issue. It seems the error occurs when `<Command.Item>` is used inside a `<For>` loop. 

cmdk applies sorting by manually reordering DOM elements, when this happens the For loop loses track of its contents and throws the error. As the error is internal to SolidJS it's hard to tell why it's triggered in this case but not others.

In my opinion, the sorting feature of this library isn't providing much value right now. It seems that filtering tends to position the desired item near the top of the results and sorting generally only shuffles the top 2 results.

I'm going to remove automatic sorting of items from the next version of the package (1.1), but sorting items can still be achieved by passing `shouldFilter={false}` to the `<Command>` element and applying filtering/sorting manually
